### ISSUE TITLE
Need to prefix a 'b' to jpg in https://github.com/kwotsin/create_tfrecords/blame/master/dataset_utils.py#L202

### ISSUE THREAD

**Issue by blahster** [kwotsin/create_tfrecords#1]
TF is expecting bytes to the 'jpg' on line 202 in dataset_utils.py
So, 
`example = image_to_tfexample(
                image_data, b'jpg', height, width, class_id)
            tfrecord_writer.write(example.SerializeToString())
`
solves the problem

**Comment by kwotsin** [comment]
Which version of TensorFlow are you running? The code still works fine on my machine running TF1.01.

**Comment by blahster** [comment]
Thank you for the code, it's very useful and works great!

I'm using TF1.0.0 with Python 3.6
Also, create_tfrecord.py isn't compatible with Python 3.6; just saying :)

**Comment by kwotsin** [comment]
Ah I see, that could be the issue! I have not really tried TF with python 3, so that could be the issue. Thanks for bringing this up! :D
