### ISSUE TITLE
dataset_utils.py _get_filenames_and_classes returns empty arrays 

### ISSUE THREAD

**Issue by Jowizo** [kwotsin/create_tfrecords#3]
Hey Kwotsin,

Thanks for this repo! I really need something like this!

I found a little problem though, the _get_filenames_and_classes() function returns empty lists for both the photo_filenames and class_names, any idea what could be wrong?

Thanks in advanced!

**Comment by kwotsin** [comment]
Hi @Jowizo, from your problem description, it seems that you might have used a different dataset_dir from what is required. For example, you could have used `/path/to/flowers/flowers_photos` instead of `/path/to/flowers` as the dataset directory. You should try the dataset_dir argument with the folder one branch above what you are currently using.


For example:
```
flowers\
    flower_photos\
        tulips\
            ....jpg
            ....jpg
            ....jpg
        sunflowers\
            ....jpg
        roses\
            ....jpg
        dandelion\
            ....jpg
        daisy\
            ....jpg
```

**Comment by Jowizo** [comment]
@kwotsin You're absolutely right!!! Can't believe I made such a silly mistake, thanks so much for your help!! Love your blog, keep it up!!

**Comment by kwotsin** [comment]
Thank you for your encouragement! Glad you have found it useful :D

**Comment by fanyuzeng** [comment]
Thank you very much!@ @kwotsin

**Comment by jmzelectronica** [comment]
Hello, I have the same mistake but I don't understant your reply, Can you explain me with an example? Please.
#State your dataset directory
flags.DEFINE_string('dataset_dir', None, 'String: /home/jmz/Dataset_flowers')

#Output filename for the naming the TFRecord file
flags.DEFINE_string('tfrecord_filename', None, 'String: /home/jmz/Documentos/Crear_Dataset/flower.tfrecord')

I have this now.
I hope your comment.

**Comment by SheezaShabbir** [comment]
Need Help I have image dataset of 26 folders............
How to give a path for such a large dataset and How to perform labeling....................
addrs, labels = zip(*c)
ValueError: not enough values to unpack (expected 2, got 0)
Getting above error again and again.............
