### ISSUE TITLE
How to decode tfrecords with images which have different sizes

### ISSUE THREAD

**Issue by MaybeShewill-CV** [kwotsin/create_tfrecords#4]
I think your method will create the tfrecords with the origin image size. Then how to decode the tfrecords with images which have different sizes. Thanks for replying.

**Comment by kwotsin** [comment]
I believe the `get_split` function from this code should be able to help you: 
https://github.com/kwotsin/transfer_learning_tutorial/blob/master/train_flowers.py

You can further see how you can train the images based on whatever model you use.

**Comment by MaybeShewill-CV** [comment]
@kwotsin Thanks for replying, after seeing train_flowers.py scripts i believe the code use slim to uniform the all tfrecords into the same size. How could i decode the tfrecords into images which have different size. Thanks a lot.

**Comment by MaybeShewill-CV** [comment]
@kwotsin Thanks a lot, I have solved the problem using sparsetensor. Have a nice day!
