### ISSUE TITLE
Resulting Files are of 0 KB

### ISSUE THREAD

**Issue by Aarijit** [kwotsin/create_tfrecords#5]
Hi,

Thanks for sharing this tfrecords creating code. I found it very useful. But when I'm running the code (I'm using exactly the same code as you shared) I'm getting 4 tfrecord files of 0 kb. 

I'm using windows and running the following code in command prompt:

`python TFRecords.py --tfrecord_filename=flowers --dataset_dir=D:/Transfer_Learning_Practice/flowers/flower_photos/`

I'm not getting any errors in the execution. The final result is 

> Finished converting the flowers dataset!

Could you please tell me where I could make the mistake?

Thank you!

**Comment by Aarijit** [comment]
Finally solved it. Based on Luka Vranjes suggestion for python 3. I need to make 2 changes in dataset_util.py file.

**Comment by animeshjn** [comment]
@Aarijit can you explain the two changes you made for Python version?

**Comment by maxhugo** [comment]
Hy Araijit 
can you tell us which changes in dataset_util were necessary?
Thanks & best regards

**Comment by Stan8** [comment]
Hello,
Can you please specify the 2 changes made in dataset_util.py ?
Thank you
